coupling_iterations_min = '5' 
coupling_iterations_max = '25' 
flowProcess = 'LIQUID_FLOW' 
massFlag = '0' 
heatFlag = '1' 

coupledFlag = '0' 
lumpingFlag = '0' 
nonlinearFlag = '0' 
solver = 'bcgs' 
